### ISSUE TITLE
Won't apply with async data on ng-table

### ISSUE THREAD

**Issue by toggm** [mike-allison/angular-tablescroll#5]
This directive doesn't work if the table content gets loaded asynchronously on an ng-table.
Just because the directive won't pass the dimensions check when linked:
 //bypass if table size smaller than given dimesions
            if (self.offsetWidth <= divWidth && self.offsetHeight <= divHeight)
                return;

self.offsetHeight is always 0 on an empty table. It should be possible to somehow repaint the table using i.e. another window event.

**Comment by mikeallisonJS** [comment]
This should be resolved with the 2.0.1 release
